# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-11 04:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_myuser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='img_profile',
            field=models.ImageField(blank=True, upload_to='user'),
        ),
    ]
