# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-11 05:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_myuser_img_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='social_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
